name: React CI Merge

on:
  workflow_run:
    types:
      - completed
    workflows:
      - 'React CI'

jobs:
  merge-pr:
    name: Merge PR
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: reitermarkus/automerge@v1
        with:
          token: ${{ secrets.AUTOMERGE_TOKEN }}
          merge-method: rebase
