name: React CI Merge

on:
  workflow_run:
    types:
      - completed
    workflows:
      - 'React CI'

jobs:
  merge-pr:
    name: Merge PR
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Merge PR
        uses: desbo/merge-pr-action@v0.3.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ALLOWED_UPDATE: any
          MERGE_METHOD: rebase
