name: React CI Merge

on:
  workflow_run:
    types:
      - completed
    workflows:
      - 'React CI'

jobs:
  merge-pr:
    name: Merge PR
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: reitermarkus/automerge@v1.5.2
        with:
        token: ${{ secrets.GITHUB_TOKEN }}
        merge-method: merge
#      - if: ${{ github.event.workflow_run.conclusion == 'success' }}
#        name: Merge Pull Request
#        uses: juliangruber/merge-pull-request-action@v1
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          number: 1
#          method: merge
